### ISSUE TITLE
How to switch deep environment to tabular environment?

### ISSUE THREAD

**Issue by bszeng** [farismismar/Q-Learning-Power-Control#3]
Hi,  I had some trouble when I was planning to simulate _Q-Learning Algorithm for VoLTE Closed Loop Power Control in Indoor Small Cells_. In order to switch to tabular environment, I did the following:
1. Change the agent class
```
from environment import radio_environment
#from DQNLearningAgent import DQNLearningAgent as QLearner # Deep with GPU and CPU fallback
from QLearningAgent import QLearningAgent as QLearner
```
2. Call the tabular function
```
#    run_agent_fpa(env)
    run_agent_tabular(env)
#    run_agent_deep(env)
```
I went through the code, but I didn't find a way to switch environments:
```
> Ep. | TS | Recv. SINR (srv) | Recv. SINR (int) | Serv. Tx Pwr | Int. Tx Pwr | Reward 
> ------------------------------------------------------------------------------------------------------------
> [-311.94796062  325.77365607  617.88366191 -146.98785931  2.94720088  13.78845061]    
> Traceback (most recent call last):
>   File "main_modify.py", line 592, in <module>
>     run_agent_tabular(env)
>   File "main_modify.py", line 56, in run_agent_tabular
>     action = agent.begin_episode(observation)
>   File "/home/nemo/workspace/Q-Learning-Power-Control/voice/QLearningAgent.py", line 52, in begin_episode
>     self.state = observation + np.zeros(self.state_size, dtype=int)
> ValueError: operands could not be broadcast together with shapes (6,) (3,) 
```

Does anyone know what to do with it?

**Comment by s-omid** [comment]
Hi, I have the same problem, did you find a solution to this?
